Sonic memory
Agustina-Carrion/hh-coding-project pull request #8
Opened 2023-05-19 20:22 UTC by Codemon72

2023-05-22 15:13 UTC, SICelineChan commented
It's a good idea and I guess we could somehow squeeze it in somewhere rather than hiding it. Like if there's gonna be another minion movie coming out or we need to drum roll for something upcoming?
The code reminds me of the hangman game, but I'm not sure **_I understood_** the whole thing just yet ;D, esp. the shufflearray function and this line -  [array[i], array[j]] = [array[j], array[i]], as in there is a difference?! Brain is a little slow after work...and there're too many conditional rendering, even a conditional rendering within a conditional rendering! ;D But there's a lot of thoughts in there, so I would say, let's not let this hardwork goes to waste ;)

2023-06-05 11:03 UTC, Agustina-Carrion requested changes

2023-06-05 11:03 UTC, Agustina-Carrion commented on src/components/SoundMatchGame.jsx
i've had some errors prompting because of the naming of the audio files. Once i've changed locally the naming to match the assets name, it all worked.
example: changed '../assets/audio/ta_da.mp3' to '../assets/audio/Ta_Da.mp3'
Does it happen to you?

2023-06-06 07:34 UTC, Codemon72 commented on src/components/SoundMatchGame.jsx
Thank you for checking it out! 🙏🤗

I think I don't understand:
The file is named 'ta_da.mp3' and it's imported with `import tadaSound from '../assets/audio/ta_da.mp3';`.
That doesn't work?

2023-06-13 19:22 UTC, Codemon72 commented on src/components/SoundMatchGame.jsx
I renamed the files with lower case. Tricky bit and surprisingly more difficult than I expected.
How does it look / work now? 🤞

2023-06-14 16:22 UTC, Agustina-Carrion approved these changes

2023-06-14 16:25 UTC, merged